### ISSUE TITLE
No Proper Invocation of AM_INIT_AUTOMAKE Was Found

### ISSUE THREAD

**Issue by P0W3** [devkitPro/dstools#5]
Using MSYS2. Trying to compile the 2022-01-25 version of dstools.

[No Proper Invocation of AM_INIT_AUTOMAKE Was Found.txt](https://github.com/devkitPro/dstools/files/10798691/No.Proper.Invocation.of.AM_INIT_AUTOMAKE.Was.Found.txt)

**Comment by WinterMute** [comment]
You need to run aclocal before you can run automake. This is why https://github.com/devkitPro/dstools/blob/master/autogen.sh exists.
